[mchalupiak]
source        = imaps://mikec@mail.mchalupiak.com
outgoing      = smtp://mikec%40mchalupiak.com@www.mchalupiak.com
default       = INBOX
from          = Michael Chalupiak <mikec@mchalupiak.com>
cache-headers = true
source-cred-cmd   = pass mikec@mchalupiak.com
outgoing-cred-cmd = pass mikec@mchalupiak.com

[mikecchalupiak]
source            = imaps+xoauth2://mikecchalupiak%40outlook.com@outlook.office365.com?
outgoing          = smtp+xoauth2://mikecchalupiak%40outlook.com@outlook.office365.com:587
from              = "Michael Chalupiak" <mikecchalupiak@outlook.com>
default           = INBOX
cache-headers     = true
source-cred-cmd   = oama access mikecchalupiak@outlook.com
outgoing-cred-cmd = oama access mikecchalupiak@outlook.com

[spamreciver1]
source            = imaps+xoauth2://spamreciver1%40outlook.com@outlook.office365.com?
outgoing          = smtp+xoauth2://spamreciver1%40outlook.com@outlook.office365.com:587
from              = "Mike Jeff" <spamreciver1@outlook.com>
default           = INBOX
cache-headers     = true
source-cred-cmd   = oama access spamreciver1@outlook.com
outgoing-cred-cmd = oama access spamreciver1@outlook.com

[chalupmc]
source            = imaps+xoauth2://chalupmc%40rose-hulman.edu@outlook.office365.com?
outgoing          = smtp+xoauth2://chalupmc%40rose-hulman.edu@outlook.office365.com:587
from              = "Michael Chalupiak" <chalupmc@rose-hulman.edu>
default           = INBOX
cache-headers     = true
source-cred-cmd   = oama access chalupmc@rose-hulman.edu
outgoing-cred-cmd = oama access chalupmc@rose-hulman.edu
