font:
  # normal:
  #   family: Cascadia Code
  #   style: Regular
  #
  # bold:
  #   family: Cascadia Code
  #   style: Bold
  #
  # italic:
  #   family: Cascadia Code
  #   style: Italic
  #
  # bold_italic:
  #   family: Cascadia Code
  #   style: Bold Italic
  #
  normal:
    family: Olympe Mono Hacked
    style: Regular
  size: 12
  # shell:
  #   program: /bin/zsh
  #   args:
  #   - --login
  #   - -c
  #   - 'tmux attach -t TMUX || tmux new -s TMUX'
# ...

# Colors (One Half Dark)
# colors:
#   primary:
#     background: '0x282c34'
#     foreground: '0xdcdfe4'

#   normal:
#     black: '0x282c34'
#     red: '0xe06c75'
#     green: '0x98c379'
#     yellow: '0xe5c07b'
#     blue: '0x61afef'
#     magenta: '0xc678dd'
#     cyan: '0x56b6c2'
#     white: '0xdcdfe4'

#   bright:
#     black: '0x282c34'
#     red: '0xe06c75'
#     green: '0x98c379'
#     yellow: '0xe5c07b'
#     blue: '0x61afef'
#     magenta: '0xc678dd'
#     cyan: '0x56b6c2'
#     white: '0xdcdfe4'


# Colors (One Half Light)
#colors:
#  primary:
#    background: '0xfafafa'
#    foreground: '0x383a42'
#
#  normal:
#    black: '0x383a42'
#    red: '0xe45649'
#    green: '0x50a14f'
#    yellow: '0xc18401'
#    blue: '0x0184bc'
#    magenta: '0xa626a4'
#    cyan: '0x0997b3'
#    white: '0xfafafa'
#
#  bright:
#    black: '0x383a42'
#    red: '0xe45649'
#    green: '0x50a14f'
#    yellow: '0xc18401'
#    blue: '0x0184bc'
#    magenta: '0xa626a4'
#    cyan: '0x0997b3'
#    white: '0xfafafa'


# Colors (Dracula)
#colors:
#  primary:
#    background: '0x282a36'
#    foreground: '0xf8f8f2'
#  cursor:
#    text: CellBackground
#    cursor: CellForeground
#  vi_mode_cursor:
#    text: CellBackground
#    cursor: CellForeground
#  search:
#    matches:
#      foreground: '0x44475a'
#      background: '0x50fa7b'
#    focused_match:
#      foreground: '0x44475a'
#      background: '0xffb86c'
#    bar:
#      background: '0x282a36'
#      foreground: '0xf8f8f2'
#  line_indicator:
#    foreground: None
#    background: None
#  selection:
#    text: CellForeground
#    background: '0x44475a'
#  normal:
#    black:   '0x000000'
#    red:     '0xff5555'
#    green:   '0x50fa7b'
#    yellow:  '0xf1fa8c'
#    blue:    '0xbd93f9'
#    magenta: '0xff79c6'
#    cyan:    '0x8be9fd'
#    white:   '0xbfbfbf'
#  bright:
#    black:   '0x4d4d4d'
#    red:     '0xff6e67'
#    green:   '0x5af78e'
#    yellow:  '0xf4f99d'
#    blue:    '0xcaa9fa'
#    magenta: '0xff92d0'
#    cyan:    '0x9aedfe'
#    white:   '0xe6e6e6'
#  dim:
#    black:   '0x14151b'
#    red:     '0xff2222'
#    green:   '0x1ef956'
#    yellow:  '0xebf85b'
#    blue:    '0x4d5b86'
#    magenta: '0xff46b0'
#    cyan:    '0x59dffc'
#    white:   '0xe6e6d1'


# Colors (Nord)
#colors:
#  primary:
#    background: '#2e3440'
#    foreground: '#d8dee9'
#    dim_foreground: '#a5abb6'
#  cursor:
#    text: '#2e3440'
#    cursor: '#d8dee9'
#  vi_mode_cursor:
#    text: '#2e3440'
#    cursor: '#d8dee9'
#  selection:
#    text: CellForeground
#    background: '#4c566a'
#  search:
#    matches:
#      foreground: CellBackground
#      background: '#88c0d0'
#    bar:
#      background: '#434c5e'
#      foreground: '#d8dee9'
#  normal:
#    black: '#3b4252'
#    red: '#bf616a'
#    green: '#a3be8c'
#    yellow: '#ebcb8b'
#    blue: '#81a1c1'
#    magenta: '#b48ead'
#    cyan: '#88c0d0'
#    white: '#e5e9f0'
#  bright:
#    black: '#4c566a'
#    red: '#bf616a'
#    green: '#a3be8c'
#    yellow: '#ebcb8b'
#    blue: '#81a1c1'
#    magenta: '#b48ead'
#    cyan: '#8fbcbb'
#    white: '#eceff4'
#  dim:
#    black: '#373e4d'
#    red: '#94545d'
#    green: '#809575'
#    yellow: '#b29e75'
#    blue: '#68809a'
#    magenta: '#8c738c'
#    cyan: '#6d96a5'
#    white: '#aeb3bb'

# Visual Bell
# ...
#background_opacity: 0.90
# Colors (Terminal.app)
# colors:
#   # Default colors
#   primary:
#     background: '0x000000'
#     foreground: '0xb6b6b6'
#
#   # Normal colors
#   normal:
#     black:   '0x000000'
#     red:     '0x990000'
#     green:   '0x00a600'
#     yellow:  '0x999900'
#     blue:    '0x0000b2'
#     magenta: '0xb200b2'
#     cyan:    '0x00a6b2'
#     white:   '0xbfbfbf'
#
#   # Bright colors
#   bright:
#     black:   '0x666666'
#     red:     '0xe50000'
#     green:   '0x00d900'
#     yellow:  '0xe5e500'
#     blue:    '0x0000ff'
#     magenta: '0xe500e5'
#     cyan:    '0x00e5e5'
#     white:   '0xe5e5e5'
# Gnome (Gnome Terminal Default)
colors:
  # Default colors
  primary:
    background: '0x1e1e1e'
    foreground: '0xffffff'

  # Normal colors
  normal:
    black:      '0x171421'
    red:        '0xc01c28'
    green:      '0x26a269'
    yellow:     '0xa2734c'
    blue:       '0x12488b'
    magenta:    '0xa347ba'
    cyan:       '0x2aa1b3'
    white:      '0xd0cfcc'

  # Bright colors
  bright:
    black:      '0x535c64'
    red:        '0xf66151'
    green:      '0x33d17a'
    yellow:     '0xe9ad0c'
    blue:       '0x2a7bde'
    magenta:    '0xc061cb'
    cyan:       '0x33c7de'
    white:      '0xffffff'
