theme = "rose_pine"

[editor]
line-number = "relative"
rulers = [80]
color-modes = true
completion-trigger-len = 1
idle-timeout = 50

[editor.statusline]
left = []
center = []
right = ["spinner", "diagnostics", "version-control", "file-modification-indicator", "file-name", "file-encoding", "read-only-indicator", "position", "mode", "selections", "spacer"]
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[editor.lsp]
display-inlay-hints = true
display-messages = true
display-progress-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal."space".e] # config mode
c = ":config-open"
l = ":e ~/.config/helix/languages.toml"
r = ":config-reload"

[keys.normal.g]
j = "goto_last_line"
k = "goto_file_start"
e = "goto_file_end"
